### ISSUE TITLE
Widgets not displaying thumbnails

### ISSUE THREAD

**Issue by jdig4240** [Helly1206/skin.xonfluence#15]
Hello, after adding a widget the thumbnails are missing and replaced with the puzzle pieces. For example adding widget for Video addons, program addons,  adding widget for Youtube (Popular now), and others. Some addons work, many dont. Links are still clickable and working in the widget, just no thumbs displayed. Swapped between Poster and Thumbnail option with same effect. Windows 10, and Android, latest 3.3.15, 17.0.

**Comment by scenicguy** [comment]
Hi, I am also having the same issue, although it is mainly with widgets created from Super Favourite Folders. As with jdig4240, some normal addons work, while some won't!
I have a build using Xonfluence on Kodi 16.1 and the widgets work perfectly, showing all thumbnails from a Super Favourites folder. The problem only exists with Xonfluence 3.3.15 on Kodi 17.0.
Helly1206, can you throw some light on this? I cannot determine if it is a problem with xonfluence or Super favourites with Kodi 17.0.

**Comment by twlizer** [comment]
Look at your settings.xml I'd assume it's because your using a build built on a PC and installed on android or Linux. Check the file paths and change from c:/user* to special://home.

This is all located in your userdata/skin.xconfluence folder settings.xml

Sent from my iPhone

On Feb 7, 2017, at 7:52 AM, jdig4240 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, after adding a widget the thumbnails are missing and replaced with the puzzle pieces. For example adding widget for Video addons, program addons, adding widget for Youtube (Popular now), and others. Some work, many dont. Links are still clickable and working in the widget, just no thumbs displayed. Swapped between Poster and Thumbnail option with same effect. Windows 10, and Android, latest 3.3.15, 17.0.

**Comment by scenicguy** [comment]
twlizer, thanks for the suggestion, but all paths in the settings.xml are set to special://home.
The build is on a PC but not yet installed on android. I have not got that far because of this problem.

**Comment by jdig4240** [comment]
No, i am aware of thumbnail paths and special directories. Thumbnails are present when browsing the directory, but are not shown in the widget. When i said video addons,, I meant the actual directory of the video addons installed for example: addons://sources/video/. If i use that as a widget to show my installed video addons, no thumbs show. Another example is adding a widget for the "Popular now" section of youtube, which definitely also has thumbs, theres no thumbs in the widget. Seem the same missing thumbs for other widgets i made also.

**Comment by AndyGHenderson** [comment]
W10 32-bit, Kodi 17.0 Xonfluence 3.3.15

My view on the issue is that I see images on the built-in widgets: Recent movies and Recent episodes but not on the widgets I created to reproduce those widgets using a playlist that constrains the list to movies/episodes contained in a specific folder. I see the Kodi-generated blue section of film instead. Problem occurs with both poster and thumbnail view.

The reference shown in the Skin settings - Home menu section for my 'New movies' widget is:
Custom: special://profile/playlists/video/New movies.xsp

Both my playlists were created through the Xonfluence UI and display images fine when I enter the playlist.

I feel a little awkward a minor issue on a really useful skin, but thought my note might help pin the problem down. I'm a developer and happy to provide any further information that might be helpful.

Andy

**Comment by jdig4240** [comment]
Well it looks like my issue with thumbnails on the widgets has been fixed in the latest update! Thanks Helly.

**Comment by AndyGHenderson** [comment]
> Well it looks like my issue with thumbnails on the widgets has been fixed in the latest update! Thanks Helly.> 

Do you mean 3.3.16? It hasn't fixed it for me. Did you have to do anything else besides install the update? I've tried everything I could think of including regenerating the playlist and widget from scratch.

Andy

**Comment by jdig4240** [comment]
Yes, my widgets all seem to be working now on 3.3.16. I did nothing extra.
[B]3.3.16[/B]
- Fixed bug on selecting weather settings in MyWeather view
- Added confluence update slideshow condition
- Updated language changes to confluence 3.0.46
- Fixed default focused menu item on graphics home menu
- Fixed not displaying thumbnail for various custom widgets

**Comment by jdig4240** [comment]
Screenshots: http://jed.one/Backgrounds/Untitled%20(3).png
http://jed.one/Backgrounds/Untitled1.png

**Comment by Helly1206** [comment]
As everything is working, I can close this issue now.

Thanks,
Helly.

**Comment by AndyGHenderson** [comment]
It's still a problem for me, I'm afraid. I have version 3.3.16 of Xonfluence, Kodi 17.0 running on Win 10 64bit.

I've tried rebuilding the playlist, favourite and widget from scratch using a different name, but still no images.

I can provide more info if you want.

Andy

**Comment by Helly1206** [comment]
Please upgrade to 3.3.17 and try again. I made some changes on thumbnails, poster, logo's on images. So I'm curious if your issue is solved by this update.

Thanks,
Helly.

**Comment by AndyGHenderson** [comment]
The new version installed automatically and it's fixed the problem for me - excellent.

Many thanks for a terrific skin.

Andy

**Comment by Helly1206** [comment]
Thanks,

I'm glad to hear this.

Helly.

**Comment by romeo5k** [comment]
@Helly1206  Can i ask for support here with a similar issue?

**Comment by Helly1206** [comment]
Sure you can ask.

Helly.
________________________________
Van: romeo5k <notifications@github.com>
Verzonden: dinsdag 5 december 2017 07:47
Aan: Helly1206/skin.xonfluence
CC: Ivo Helwegen; Mention
Onderwerp: Re: [Helly1206/skin.xonfluence] Widgets not displaying thumbnails (#15)


@Helly1206<https://github.com/helly1206> Can i ask for support here with a similar issue?

**Comment by romeo5k** [comment]
Lemme try to make it short, last time i tried to write ask, it was like 10 lines..
I wanted widgets to work. So i did as i was told by others, add the location to favorites and , then in widget-Custom settings, add it from Favorites. Well it doesnt work for me.
But if i add widgets by typing in the url , that works, but its not to the actual location i want. Its to a set of categories. Why isnt widget working when i use favorites? Is there a setting thats not activated?

[https://youtu.be/stgVUIJ3dqA](url)

**Comment by Helly1206** [comment]
Hi,

I've seen your movie and indeed adding widgets from favourites doesn't seem to work for you. I tried but I cannot reproduce this behaviour. At my systems it just works.

Maybe a stupid question but did you press enter after selecting the favourite, not escape or cancel?

You can have a look at the logfile (or send it to me), maybe that will give a clue.

Helly.
________________________________
Van: romeo5k <notifications@github.com>
Verzonden: vrijdag 8 december 2017 02:35
Aan: Helly1206/skin.xonfluence
CC: Ivo Helwegen; Mention
Onderwerp: Re: [Helly1206/skin.xonfluence] Widgets not displaying thumbnails (#15)


Lemme try to make it short, last time i tried to write ask, it was like 10 lines..
I wanted widgets to work. So i did as i was told by others, add the location to favorites and , then in widget-Custom settings, add it from Favorites. Well it doesnt work for me.
But if i add widgets by typing in the url , that works, but its not to the actual location i want. Its to a set of categories. Why isnt widget working when i use favorites? Is there a setting thats not activated?

https://youtu.be/stgVUIJ3dqA<url>

**Comment by romeo5k** [comment]
hmm.. Okay, youre the 3rd person who could not recreate this. So before i send the error log, im going  start over from scratch and delete the whole firestick and start over,... Maybe there is a setting i touched that i shouldnt have..

**Comment by Helly1206** [comment]
Ok, success. Please keep me informed.

Helly.
________________________________
Van: romeo5k <notifications@github.com>
Verzonden: vrijdag 8 december 2017 20:50
Aan: Helly1206/skin.xonfluence
CC: Ivo Helwegen; Mention
Onderwerp: Re: [Helly1206/skin.xonfluence] Widgets not displaying thumbnails (#15)


hmm.. Okay, youre the 3rd person who could not recreate this. So before i send the error log, im going start over from scratch and delete the whole firestick and start over,... Maybe there is a setting i touched that i shouldnt have..

**Comment by xcsresources** [comment]
Xonfluence skin using an Android box with Kodi 17.6.. 5 or so days ago, the selected-favorites option stopped adding widgets in the skin. Ive searched everywhere for an easy fix, only to find nothing. The custom is usable but I dont know the paths. Any insight as to why it would suddenly stop recognizing selected favorites to add widgets?
